Caught itexception: null
java.lang.reflect.InvocationTargetException
	at InvTarExcTest.main(13)
Target is: throwing inner exception
