Caught itexception: null
java.lang.reflect.InvocationTargetException
	at InvTarExcTest.main(InvTarExcTest.java:13)
Target is: throwing inner exception
